services:
  - type: web
    name: laravel-demo
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan key:generate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
